services:
  reverb:
    #>               docker compose -f docker-compose.build.yml build --pull reverb
    #rebuild:clean>  docker compose -f docker-compose.build.yml build --pull --no-cache reverb
    #push>           docker compose -f docker-compose.build.yml push reverb
    image: 0imbn7v6rkw/websockets-server-reverb:1.0.0
    build:
      context: .
      dockerfile: Dockerfile

    env_file: ./.env
    environment:

      APP_ENV: production
      APP_DEBUG: "false"

      # single-container wiring
      DB_HOST: 127.0.0.1
      REDIS_HOST: 127.0.0.1
      DB_PORT: 5432

      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: app

      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app

      CACHE_STORE: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      BROADCAST_CONNECTION: reverb

      RUN_MIGRATIONS: "true"
      CACHE_ARTISAN: "true"

    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - redisdata:/data

    restart: unless-stopped
    stop_grace_period: 60s

volumes:
  pgdata:
  redisdata:
